services:
  - type: web
    name: fastapi
    runtime: docker 
    plan: free
    repo: https://github.com/arysttoto/helpmesolve_back.git
    region: frankfurt
    branch: main 
    envVars:
      - key: OPEN_AI_TOKEN
        sync: false   
      - key: PINECONE_API_TOKEN
        sync: false 
      - key: SERPAPI_API_KEY
        sync: false 
      - key: PINECONE_API_ENV
        sync: false 
    buildFilter:
      paths:
      - app/**    